<?php

namespace App\Resource;

use Core\Response\JsonResponse;

class UsersListResource extends JsonResponse
{
    /**
     * @return array
     */
    public function toArray(): array
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}